/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'groceries' : IDL.Null,
  'snacks' : IDL.Null,
  'beverages' : IDL.Null,
  'personalCare' : IDL.Null,
  'dairy' : IDL.Null,
  'household' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : ProductCategory,
  'priceInr' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, ProductCategory, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getStoreInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'hours' : IDL.Text,
          'name' : IDL.Text,
          'address' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'initializeProducts' : IDL.Func([], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'searchProductsByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateStoreInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'groceries' : IDL.Null,
    'snacks' : IDL.Null,
    'beverages' : IDL.Null,
    'personalCare' : IDL.Null,
    'dairy' : IDL.Null,
    'household' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : ProductCategory,
    'priceInr' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, ProductCategory, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStoreInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'hours' : IDL.Text,
            'name' : IDL.Text,
            'address' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'initializeProducts' : IDL.Func([], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'searchProductsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'updateStoreInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };