/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Product {
  'id' : bigint,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'category' : ProductCategory,
  'priceInr' : bigint,
}
export type ProductCategory = { 'groceries' : null } |
  { 'snacks' : null } |
  { 'beverages' : null } |
  { 'personalCare' : null } |
  { 'dairy' : null } |
  { 'household' : null };
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, ProductCategory, bigint, string, bigint],
    bigint
  >,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getStoreInfo' : ActorMethod<
    [],
    { 'hours' : string, 'name' : string, 'address' : string, 'phone' : string }
  >,
  'initializeProducts' : ActorMethod<[], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'searchProductsByName' : ActorMethod<[string], Array<Product>>,
  'updateStoreInfo' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];